# Generated by Django 5.0.7 on 2024-11-26 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_bids_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('SHIRT', 'Shirt'), ('T_SHIRT', 'T-Shirt'), ('HOODIE', 'Hoodie'), ('FOOTWEAR', 'Footwear'), ('PANTS', 'Pants')], max_length=100, null=True),
        ),
    ]
